SqLite Support
denisenko93/Dommel.Bulk pull request #3
Opened 2022-06-17 10:01 UTC by MMaximus111

2022-06-18 14:21 UTC, denisenko93 requested changes

2022-06-18 14:21 UTC, denisenko93 commented on src/Dommel.Bulk/DatabaseAdapters/SqLiteDatabaseAdapter.cs
> +        [typeof(DateTime)] = new GenericTypeMapper<DateTime>((x, tw) => tw.WriteSqLiteDateTime(x, true)),
SqLite supports date storage in 3 formats. We must document the date format used for insertion

2022-06-18 14:21 UTC, denisenko93 commented on src/Dommel.Bulk/DatabaseAdapters/SqLiteDatabaseAdapter.cs
> +    private static readonly Dictionary<Type, ITypeMapper> TypeMappers = new Dictionary<Type, ITypeMapper>
SqLite supports storing an array of bytes in the `BLOB` type. We must implement support for this type

2022-06-18 14:21 UTC, denisenko93 commented on src/Dommel.Bulk/DatabaseAdapters/SqLiteDatabaseAdapter.cs
> +            textWriter.Write(sqlBuilder.QuoteIdentifier(constraintName));
You need to check that `constraintName` is not empty

2022-06-18 14:21 UTC, denisenko93 commented on src/Dommel.Bulk/Extensions/SqLiteTextWriterExtensions.cs
> +public static class SqLiteTextWriterExtensions
Extensions must be `internal`

2022-06-18 14:21 UTC, denisenko93 commented on tests/Dommel.Bulk.IntegrationTests/Dommel.Bulk.IntegrationTests.csproj
> +        <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.5" />
There are two popular sqlite connectors. System.Data.SQLite.Core and Microsoft.Data.Sqlite.Core. I think it is necessary to write unit tests using both libraries

2022-06-18 17:20 UTC, denisenko93 requested changes

2022-06-18 17:20 UTC, denisenko93 commented on tests/Dommel.Bulk.IntegrationTests/SqLiteBulkInsertTests.cs
> +        SqlMapper.AddTypeHandler(new GuidHandler());
I think this behavior should be documented. You can also add a setting that fixes the problem.

2022-06-19 12:46 UTC, MMaximus111 commented
All fixes done.

2022-06-19 13:29 UTC, denisenko93 requested changes

2022-06-19 13:29 UTC, denisenko93 commented on tests/Dommel.Bulk.IntegrationTests/SqLiteBulkInsertTests.cs
> +        yield return new SqliteConnection(@"Data Source=C:\Users\Admin\DataGripProjects\Telemart\identifier.sqlite");
Path to identifier.sqlite must be relative

2022-06-19 13:29 UTC, denisenko93 commented on tests/Dommel.Bulk.IntegrationTests/BulkInsertTestsBase.cs
> +        foreach (IDbConnection connection in GetOpenConnections())
Only one connection should be available in the test case

2022-06-19 20:55 UTC, MMaximus111 commented
Done.

2022-11-06 14:19 UTC, denisenko93 approved these changes

2022-11-06 14:19 UTC, merged